linters:
  enable-all: true
  disable:
    - ifshort
    - structcheck
    - interfacer
    - nosnakecase
    - maligned
    - deadcode
    - varcheck
    - exhaustivestruct
    - scopelint
    - golint
    - gomnd
    - gofumpt
    - gci
    - dogsled
    - forbidigo
    - depguard
    - goimports

linters-settings:
  varnamelen:
    max-distance: 10