name: advent-of-code
channels:
  - defaults
dependencies:
  - python=3.12
  - networkx
  - shapely
  - more-itertools
  - regex
  - numpy
  - numba
  - conda-forge::pre-commit
  - conda-forge::notebook
  - conda-forge::seaborn
  - sympy
